#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Better ls coloring when using solarized terminal theme
# Start by figuring out where dircolors is, by figuring out where this file is
location=$(readlink -f ${(%):-%N})
eval $(eval "gdircolors ~/dircolors-solarized/dircolors.ansi-dark")
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# Set terminal
export TERM=xterm-256color

# Ensure that external editor launches correctly
export VISUAL=vimx

alias ls='gls --color=auto'
