#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# This loads nvm
export NVM_DIR="/Users/Jake/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Load RVM into a shell session *as a function*
# [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Load chruby
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh
RUBIES+=(~/.rvm/rubies/*)

# Better ls coloring when using solarized terminal theme
# Start by figuring out where dircolors is, by figuring out where this file is
location=$(readlink -f ${(%):-%N})
eval $(eval "gdircolors ~/dircolors-solarized/dircolors.ansi-dark")
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# Set terminal
export TERM=xterm-256color

# Ensure that external editor launches correctly
export VISUAL=vimx

alias ls='gls --color=auto'
